CodeGram/Controllers/FriendsController.cs
using CodeGram.Controllers.Base;
using CodeGram.Data.Helpers.Constants;
using CodeGram.Data.Services;
using CodeGram.ViewModel.Friends;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodeGram.Controllers
{
    [Authorize(Roles = AppRoles.User)]
    public class FriendsController : BaseController
    {
        private readonly IFriendsService _friendsService;
        private readonly INotificationsService _notificationsService;

        public FriendsController(IFriendsService friendsService, INotificationsService notificationsService)
        {
            _friendsService = friendsService;
            _notificationsService = notificationsService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = GetUserId();
            if (!userId.HasValue) RedirectToLogin();

            var friendsData = new FriendshipVM
            {
                Friends = await _friendsService.GetFriendsAsync(userId.Value),
                FriendRequestsSent = await _friendsService.GetSentFriendRequestAsync(userId.Value),
                FriendRequestsReceived = await _friendsService.GetReceivedFriendRequestAsync(userId.Value)
            };

            return View(friendsData);
        }

        [HttpPost]
        public async Task<IActionResult> SendFriendRequest(int receiverId)
        {
            var userId = GetUserId();
            var userName = GetUserFullName();

            if (!userId.HasValue) RedirectToLogin();

            await _friendsService.SendRequestAsync(userId.Value, receiverId);

            await _notificationsService.AddNewNotificationAsync(receiverId, NotificationType.FriendRequest, userName, null);

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveFriend(int friendshipId)
        {
            await _friendsService.RemoveFriendAsync(friendshipId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFriendRequest(int requestId, string status)
        {
            var userId = GetUserId();
            var userName = GetUserFullName();

            if (!userId.HasValue) RedirectToLogin();

            var request = await _friendsService.UpdateRequestAsync(requestId, status);

            if (status == FriendshipStatus.Accepted)
            {
                await _notificationsService.AddNewNotificationAsync(request.SenderId, NotificationType.FriendRequestApproved, userName, null);
            }

            return RedirectToAction("Index");
        }
    }
}

CodeGram/Controllers/NotificationsController.cs
using CodeGram.Controllers.Base;
using CodeGram.Data.Helpers.Constants;
using CodeGram.Data.Models;
using CodeGram.Data.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CodeGram.Controllers
{
    [Authorize(Roles = AppRoles.User)]
    public class NotificationsController : BaseController
    {
        private readonly INotificationsService _notificationsService;
        public NotificationsController(INotificationsService notificationsService)
        {
            _notificationsService = notificationsService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetCount()
        {
            var userId = GetUserId();

            if (!userId.HasValue) RedirectToLogin();

            var count = await _notificationsService.GetUnreadNotificationsCountAsync(userId.Value);

            return Json(count);
        }

        [HttpGet]
        public async Task<IActionResult> GetNotifications()
        {
            var userId = GetUserId();

            if (!userId.HasValue) RedirectToLogin();

            var notifications = await _notificationsService.GetNotifications(userId.Value);

            return PartialView("Notifications/_Notifications", notifications);
        }

        [HttpPost]
        public async Task<IActionResult> SetNotificationAsRead(int notificationId)
        {
            var userId = GetUserId();

            if (!userId.HasValue) RedirectToLogin();

            await _notificationsService.SetNotificationAsRead(notificationId);

            var notifications = await _notificationsService.GetNotifications(userId.Value);

            return PartialView("Notifications/_Notifications", notifications);
        }
    }
}

CodeGram/Views/Shared/Notifications/_Notifications.cshtml
@model List<Notification>

@foreach(var notification in @Model)
{
    TimeSpan time = DateTime.UtcNow.Subtract(notification.DateCreated);
    string displayTxt = time switch
    {
        var t when t.TotalDays >= 1 => $"{(int)t.TotalDays}d ago",
        var t when t.TotalHours >= 1 => $"{(int)t.TotalHours}h ago",
        var t when t.TotalMinutes >= 1 => $"{(int)t.TotalMinutes}m ago",
        _ => "Just now"
    };

    string iconName = notification.Type switch
    {
        NotificationType.Favorite => "bookmark-outline",
        NotificationType.Like => "heart-outline",
        NotificationType.Comment => "chatbubbles-outline",
        NotificationType.FriendRequest => "person-add-outline",
        NotificationType.FriendRequestApproved => "person-outline",
        _ => "notifications-outline"

    };

    string redirectUrl = notification.Type switch
    {
        NotificationType.FriendRequest => Url.Action("Index", "Friends"),
        NotificationType.FriendRequestApproved => Url.Action("Index", "Friends"),
        _ => Url.Action("Details", "Home", new  { postId = notification.PostId } )
    };


    <div class="relative flex items-center gap-3 p-2 duration-200 rounded-xl pr-10 hover:bg-secondery @(notification.IsRead ? "" : "bg-teal-500/5")">
        <div class="flex items-center gap-2 flex-1">
            <ion-icon name="@iconName" class="text-2xl"></ion-icon>
            <div>
                <p>
                    <a href="@redirectUrl">
                        @if (notification.IsRead)
                        {
                            @notification.Message
                        }
                        else
                        {
                            <b class="font-bold mr1">
                                @notification.Message
                            </b>
                        }
                    </a>

                </p>
                <div class="text-xs text-gray-500 mt-1.5">@displayTxt</div>

            </div>

            @if (notification.IsRead == false)
            {
                <div class="w-2.5 h-2.5 bg-teal-600 rounded-full absolute right-3 top-5" onclick="setNotificationAsRead(@notification.Id)"></div>
            }

        </div>
    </div>
}